### ISSUE TITLE
Smoke test from tutorial fails

### ISSUE THREAD

**Issue by rkjaran** [burrmill/burrmill#11]
### I wanted to achieve this:
Perform the smoke test in the tutorial.

### So I did this:
Used `sudo -u slurm scontrol update nodename=qw-node-n2-1 state=POWER_UP` on `qw-login` to power up the the appropriate  node.

### And expected that
It enters the `POWER_UP` state and finally become available (and idle).

### But actual result was
The journal for `slurmctld` shows `powering up node qw-node-n2-1` but never `Node qw-node-n2-1 now responding`

### I think that the following info is relevant:
If I run run ` /usr/local/sbin/slurm_resume.sh qw-node-n2-1` manually on `qw-control` I get an error

    /usr/local/sbin/slurm_resume.sh: line 28: BURRMILL_CLUSTER: unbound variable

So I set `BURRMILL_CLUSTER` to `qw` and run `slurm_resume.sh` again which now powers the node up as expected.

**Comment by rkjaran** [comment]
I missed the following in the journal for `slurmctld`:

    error: power_save module disabled, invalid SuspendProgram /usr/local/sbin/slurm_suspend.sh

If I change the permissions with `chmod og-w /usr/local/sbin/slurm_{resume,suspend}.sh` the node enters the `POWER_UP` state (`idle#` in `sinfo`) but now `$GCI create` command fails and the node never powers up.

**Comment by kkm000** [comment]
Thanks for testing! We just ran into these two problems too. Another couple fixes are coming, you'll need to rebuild the base image. The fix to the second one is simple, but there is another problem with NVIDIA driver build, so please just hold on.

What's your experience in general? Overwhelming, or you can more or less make sense of it? Do you have any previous GCP experience? Any feedback is very welcome!

**Comment by kkm000** [comment]
I'm trying to pinpoint the `g+w` bit issue. It appears the file ended up in the tarball with the bit already set. What OS/distro were you using, and what was the tar version? This info would be helpful:

$ uname -srvmo
$ lsb_release -a
$ tar --version

Thanks!

**Comment by kkm000** [comment]
@jtrmal, could you please answer the above questions, too? I never thought that I would be reading tar sources ever. Cannot repro, whatever I do. The more you know...

**Comment by rkjaran** [comment]
I've been using a setup based on https://github.com/SchedMD/slurm-gcp but it's
just not a great fit for the Kaldi way of doing things. This projects seems to
be exactly what I'm looking for and everything seems pretty straight forward.

Here's the version info:

``` 
$ uname -srvmo 
Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 GNU/Linux
```

```
$  lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

```
$  tar --version 
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

```
$  tar --help | tail -5
  clocale

*This* tar defaults to:
--format=gnu -f- -b20 --quoting-style=escape --rmt-command=/usr/sbin/rmt
--rsh-command=/usr/bin/rsh
```

**Comment by jtrmal** [comment]
I wish I was able to help, but this is above my head. But I'm watching you
both :)
y.

**Comment by kkm000** [comment]
@jtrmal, if you pull your tar.gz files, they have xwrxwrx-r on all /usr/local/sbin executables and the directory itself, and an extra g+w for the only non-executable. In fact, I suspect that group right bits are same as owner's bits for all files in these tarballs. And I have absolutely no idea how that could have happened. I tried even git for Windows shell and busybox. Are you also using ubuntu 20?

My tar(1) is completely identical, version, build flags and the kitchen sink.

@jtrmal, @rkjaran, could you please check the files in lib/imaging/layouts/compute/usr/local/sbin? They are simply packaged from that directory, totally no frills. And I already know that the tarballs uploaded by daisy have the freaking bit set, so what happens later is irrelevant.

I do not think both of you use a filesystem that does not distinguish between owner and group bits? Plain old good ext4? The Git repo has them correct, my checkout has them correct. Looks like I need some ideas...

I'll spin off an Ubuntu VM and see.

@rkjaran, yes, SchedMD script is nothing but a demo. Burmill is highly optimized for the real work, cost/throughput mainly, but has quite a throughput. Unfortunately, it is a little bit on the overengineered side, to smooth the learning curve. But after 6 months on a backburner, we are having trouble deploying our own clusters right now, because little things change in GCP all the time. So we are fixing it the full steam. I have a fix for one of the problems already. We hit a couple more _interesting_ ones. Your feedback regarding the tarball issue would be very helpful.

In fact, when I run `bm-os-image bu` [ild], I see this--the quick scrolling of the tarball contents hits the slower daisy startup, and the last lines that _I_ see are nominal:
```
drwxr-xr-x root/root         0 2020-04-12 19:43 ./usr/
drwxr-xr-x root/root         0 2020-04-12 19:43 ./usr/local/
drwxr-xr-x root/root         0 2020-09-30 03:33 ./usr/local/sbin/
-rwxr-xr-x root/root       761 2020-04-12 19:43 ./usr/local/sbin/clusterid_from_metadata
-rwxr-xr-x root/root      2487 2020-04-12 19:43 ./usr/local/sbin/create-uvm-dev-node
-rwxr-xr-x root/root       528 2020-04-12 19:43 ./usr/local/sbin/is_host_in_cluster
-rwxr-xr-x root/root       314 2020-04-12 19:43 ./usr/local/sbin/nfsd_poststart
-rwxr-xr-x root/root      4334 2020-09-30 03:33 ./usr/local/sbin/nfsd_prestart_oobe
-rwxr-xr-x root/root      1066 2020-04-12 19:43 ./usr/local/sbin/opt_postmount
-rw-r--r-- root/root       980 2020-10-30 03:13 ./usr/local/sbin/slurm_common.inc.sh
-rwxr-xr-x root/root      1757 2020-04-12 19:43 ./usr/local/sbin/slurm_poststart_config
-rwxr-xr-x root/root      2683 2020-04-12 19:43 ./usr/local/sbin/slurm_prestart_config
-rwxr-xr-x root/root      3898 2020-04-12 19:43 ./usr/local/sbin/slurm_resume.sh
-rwxr-xr-x root/root       457 2020-10-30 03:14 ./usr/local/sbin/slurm_suspend.sh
-rwxr-xr-x root/root      1139 2020-04-12 19:43 ./usr/local/sbin/slurm_trigger_node_down_recover.sh
-rwxr-xr-x root/root       477 2020-04-12 19:43 ./usr/local/sbin/update_known_hosts
```
So the problem should be apparent there already.

**Comment by jtrmal** [comment]
I am actually running ext4
y.

**Comment by kkm000** [comment]
@jtrmal 
> I think the ubuntu's umask is by default 0002
Git should keep the flags. Now we know the culprit. I'll figure out.

**Comment by kkm000** [comment]
Yes, it's an umask issue. Possible workaround:
```
git -c tar.umask=0022 -C .... archive HEAD . | tar tvv
```

**Comment by kkm000** [comment]
Ok, the right fix is to use the `--mode=go-w` to `tar`. I checked a few docker images of the oldest version of most popular distros, and all of them come with a GNU tar recent enough to have this option (except Alpine, of course) : ).

Hold on.
